{
 "title": "Rancher Performance Debugging",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Handler Average Execution Times Over Last 5 Minutes (Top 20)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Execution Time in Seconds" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum by (handler_name) (rate(lasso_controller_reconcile_time_seconds_sum[5m]))\n/\nsum by (handler_name) (rate(lasso_controller_reconcile_time_seconds_count[5m])))",
     "legendFormat": "{{handler_name}}"
    }
   ]
  },
  {
   "title": "Rancher API Average Request Times Over Last 5 Minutes (Top 20) (Subscribes Omitted)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum by (resource, method, code) (rate(steve_api_request_time_sum{resource!=\"subscribe\"}[5m]))\n/\nsum by (resource, method, code) (rate(steve_api_request_time_count{resource!=\"subscribe\"}[5m])))",
     "legendFormat": "{{resource}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Subscribe Average Request Times Over Last 5 Minutes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(steve_api_request_time_sum{resource=\"subscribe\"}[5m])\n/\nrate(steve_api_request_time_count{resource=\"subscribe\"}[5m])",
     "legendFormat": "{{resource}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Lasso Controller Work Queue Depth (Top 20)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "topk(20,workqueue_depth)", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Number of Rancher Requests (Top 20)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum by (id, resource, method, code) (steve_api_total_requests))",
     "legendFormat": "{{id}} {{resource}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Number of Failed Rancher API Requests (Top 20)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum by (id, resource, method) (steve_api_total_requests{code!=\"200\",code!=\"201\"}))",
     "legendFormat": "{{id}} {{resource}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "K8s Proxy Client Average Request Times Over Last 5 Minutes (Top 20)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum by (resource, method, code) (rate(k8s_proxy_client_request_time_sum[5m]))\n/\nsum by (resource, method, code) (rate(k8s_proxy_client_request_time_count[5m])))",
     "legendFormat": "{{resource}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "K8s Proxy Store Average Request Times Over Last 5 Minutes (Top 20)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum by (resource, method, code) (rate(k8s_proxy_store_request_time_sum[5m]))\n/\nsum by (resource, method, code) (rate(k8s_proxy_store_request_time_count[5m])))",
     "legendFormat": "{{resource}} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Lasso Handler Executions (Top 20)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum by (handler_name) (\nlasso_controller_total_handler_execution\n))",
     "legendFormat": "{{handler_name}}"
    }
   ]
  },
  {
   "title": "Total Handler Executions with Error (Top 20)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum by (handler_name) (\nlasso_controller_total_handler_execution{has_error=\"true\"}\n))",
     "legendFormat": "{{handler_name}}"
    }
   ]
  },
  {
   "title": "Cached Objects by GroupVersionKind (Top 20)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,lasso_controller_total_cached_object)",
     "legendFormat": "{{kind}} {{version}} {{group}} {{pod}}"
    }
   ]
  },
  {
   "title": "Handler Executions Over Last 2 Minutes (Top 20)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum by (handler_name,controller_name) (\nincrease(lasso_controller_total_handler_execution[2m])\n))",
     "legendFormat": "{{controller_name}}.{{handler_name}}"
    }
   ]
  },
  {
   "title": "Handler Executions Over Last 2 Minutes (Top 20)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20,sum by (handler_name,controller_name) (\nincrease(lasso_controller_total_handler_execution{has_error=\"true\"}[2m])\n))",
     "legendFormat": "{{controller_name}}.{{handler_name}}"
    }
   ]
  },
  {
   "title": "Data Transmitted by Remote Dialer Sessions (Top 20)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(20,session_server_total_transmit_bytes)",
     "legendFormat": "{{clientkey}} {{pod}}"
    }
   ]
  },
  {
   "title": "Errors for Remote Dialer Sessions (Top 20)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ms", "label": "Error Data" }
   ],
   "targets": [
    {
     "expr": "session_server_total_transmit_error_bytes",
     "legendFormat": "{{clientkey}} {{pod}}"
    }
   ]
  },
  {
   "title": "Remote Dialer Connections Removed (Top 20)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "session_server_total_remove_connections",
     "legendFormat": "{{clientkey}} {{pod}}"
    }
   ]
  },
  {
   "title": "Remote Dialer Connections Added by Client (Top 20)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "session_server_total_add_connections",
     "legendFormat": "{{clientkey}} {{pod}}"
    }
   ]
  }
 ]
}